version = 0.1
[default.deploy.parameters]
stack_name = "sam-inventory"
resolve_s3 = true
s3_prefix = "sam-inventory"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=\"dev\""
image_repositories = []
